### ISSUE TITLE
能否提供一下模型权重文件？

### ISSUE THREAD

**Issue by 0-Maxwei-0** [Gorilla-Lab-SCUT/TRIBE#1]
您好，感谢您的工作。我在运行
`python GLI_TTA.py \
      -acfg configs/adapter/TRIBE.yaml \
      -dcfg configs/dataset/cifar10.yaml \
      -pcfg configs/protocol/gli_tta.yaml \
      OUTPUT_DIR TRIBE/cifar10
`
时，提示下载
`Download started: path=ckpt/cifar10/corruptions/Standard.pt (gdrive_id=1t98aEuzeTL8P7Kpd5DIrCoCL21BNZUhC)`
但出现链接超时问题，无法下载，能否提供一下本地的下载链接？谢谢！

**Comment by Dyb3438** [comment]
Hello @0-Maxwei-0,

For your convenience to run our released code, we provide downloadable checkpoints at the [OneDrive Space](https://1drv.ms/u/s!AlvmlyfvwRfJlhM7hNMqJlzviNNA?e=tBZRu5). You can easily download the used checkpoint for CIFAR10 and CIFAR100 through this link, if you can't get the checkpoints via automatic download from `robustbench`. The checkpoint for ImageNet is provided by `torchvision` so we wouldn't put it into the OneDrive.

Good luck!

Su Yongyi

**Comment by 0-Maxwei-0** [comment]
> Hello @0-Maxwei-0,
> 
> For your convenience to run our released code, we provide downloadable checkpoints at the [OneDrive Space](https://1drv.ms/u/s!AlvmlyfvwRfJlhM7hNMqJlzviNNA?e=tBZRu5). You can easily download the used checkpoint for CIFAR10 and CIFAR100 through this link, if you can't get the checkpoints via automatic download from `robustbench`. The checkpoint for ImageNet is provided by `torchvision` so we wouldn't put it into the OneDrive.
> 
> Good luck!
> 
> Su Yongyi

thanks again!
